export enum AuthorityEnum {
    VIEW_CARD_ORDER = 'VIEW_CARD_ORDER',
    VIEW_POINT_TRANSACTION = 'VIEW_POINT_TRANSACTION',
    UPDATE_CARD_ORDER = 'UPDATE_CARD_ORDER',
    VIEW_CARD = 'VIEW_CARD',
    CREATE_CARD = 'CREATE_CARD',
    UPDATE_CARD = 'UPDATE_CARD',
    DELETE_CARD = 'DELETE_CARD',
    VIEW_CARD_CONFIGURATION = 'VIEW_CARD_CONFIGURATION',
    UPDATE_CARD_CONFIGURATION = 'UPDATE_CARD_CONFIGURATION',
    VIEW_LOCK_FEATURE = 'VIEW_LOCK_FEATURE',
    UPDATE_LOCK_FEATURE = 'UPDATE_LOCK_FEATURE'
}