export { default as ClientCatalogSelect } from './client-catalog-select'
export { ClientMenuItem } from './client-menu-item'
export { ClientMenus } from './client-menus'
export { default as DualRangeSlider } from './dual-range-slider'
export { default as PriceRangeFilter } from './price-range-filter'
export { default as ProductImageCarousel } from './product-image-carousel'
export { default as ProductNameSearch } from './product-name-search'
export { default as SliderRelatedProducts } from './slider-related-products'
// export { default as SliderRelatedProducts } from './slider-related-products'

